'''<br><br>


    @Author: Shivraj Yelave
    @Date: 5-08-24
    @Last modified by: Shivraj Yelave
    @Last modified time:
    @Title: Python Numpy Programs 
<br><br>


'''

In [12]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. <br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32] <br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [13]:
def main():
    lst = [12.23, 13.32, 100, 36.32]
    arr = np.array(lst)
    print("Array:",arr)

if __name__ == '__main__':
    main()

Array: [ 12.23  13.32 100.    36.32]


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]


In [18]:
def main():
    arr = np.arange(2,11)
    print("3x3 Array: \n",arr.reshape(3,3))
if __name__ == '__main__':
    main()

3x3 Array: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 4. Write a Python program to reverse an array (first element becomes last).
Original array: <br>
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] <br>
Reverse array: <br>
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [19]:
def main():
    lst = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
    arr =  np.array([lst])
    arr=arr[::-1]
    print("Reversed array:",arr)
if __name__ == '__main__':
    main()

Reversed array: [[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
  36 37]]


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output: <br>
Original array: <br>
[[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.]] <br>
1 on the border and 0 inside in the array <br>
[[ 1. 1. 1. 1. 1.] <br>
[ 1. 0. 0. 0. 1.] <br>
[ 1. 0. 0. 0. 1.] <br>
[ 1. 0. 0. 0. 1.] <br>
[ 1. 1. 1. 1. 1.]] <br>


In [30]:
def main():
    arr = np.ones((5,5))
    arr[1:-1,1:-1]=0
    print("Required array:\n",arr)
if __name__ == '__main__':
    main()

Required array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output: <br>
Original array: <br>
[[ 1. 1. 1.] <br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]

In [34]:
def main():
    arr = np.ones((3,3))
    arr = np.pad(arr,pad_width=1,constant_values=0)
    print(arr)
if __name__ == '__main__':
    main()

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]

In [41]:
def main():
    arr = np.array([])
    print(arr)
if __name__ == '__main__':
    main()

NameError: name 'm' is not defined