'''<br><br>


    @Author: Shivraj Yelave
    @Date: 5-08-24
    @Last modified by: Shivraj Yelave
    @Last modified time:
    @Title: Python Numpy Programs 
<br><br>


'''

In [2]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. <br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32] <br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [13]:
def main():
    lst = [12.23, 13.32, 100, 36.32]
    arr = np.array(lst)
    print("Array:",arr)

if __name__ == '__main__':
    main()

Array: [ 12.23  13.32 100.    36.32]


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]


In [18]:
def main():
    arr = np.arange(2,11)
    print("3x3 Array: \n",arr.reshape(3,3))
if __name__ == '__main__':
    main()

3x3 Array: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 4. Write a Python program to reverse an array (first element becomes last).
Original array: <br>
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] <br>
Reverse array: <br>
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [19]:
def main():
    lst = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
    arr =  np.array([lst])
    arr=arr[::-1]
    print("Reversed array:",arr)
if __name__ == '__main__':
    main()

Reversed array: [[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
  36 37]]


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output: <br>
Original array: <br>
[[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.] <br>
[ 1. 1. 1. 1. 1.]] <br>
1 on the border and 0 inside in the array <br>
[[ 1. 1. 1. 1. 1.] <br>
[ 1. 0. 0. 0. 1.] <br>
[ 1. 0. 0. 0. 1.] <br>
[ 1. 0. 0. 0. 1.] <br>
[ 1. 1. 1. 1. 1.]] <br>


In [64]:
def main():
    arr = np.ones((5,5))
    arr[1:-1,1:-1]=0
    print("Required array:\n",arr)
if __name__ == '__main__':
    main()

Required array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output: <br>
Original array: <br>
[[ 1. 1. 1.] <br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]

In [34]:
def main():
    arr = np.ones((3,3))
    arr = np.pad(arr,pad_width=1,constant_values=0)
    print(arr)
if __name__ == '__main__':
    main()

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]

In [43]:
def main():
    arr = np.array([[(rows+col)%2 for rows in range(8)] for col in range(8) ])
    print(arr)
if __name__ == '__main__':
    main()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 8. Write a Python program to convert a list and tuple into arrays.
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>


In [70]:

def convert_to_array(input):
    """
    Description:
    Convert the input into a array.

    Parameters:
        input (various types): The input to be converted into a array.
    
    Returns:
        list: The converted array.
    """
    return np.array(input)

def main():
    # Create a list and convert it to a NumPy array
    lst = [number + 1 for number in range(8)]
    
    # Create a tuple and convert it to a NumPy array, then reshape
    tuple = (8, 4, 6, 1, 2, 3)
    
    # Test the convert_to_list function
    print("List converted to array:\n", convert_to_array(lst))
    print("Tuple converted to array:\n", np.reshape(convert_to_array(tuple),(2,3)))

if __name__ == '__main__':
    main()


List converted to array:
 [1 2 3 4 5 6 7 8]
Tuple converted to array:
 [[8 4 6]
 [1 2 3]]


## 9. Write a Python program to append values to the end of an array.
Expected Output:<br>
Original array:<br>
[10, 20, 30]<br>
After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]<br>


In [89]:
def append_values(arr, number_of_values):
    """
    Description:
    Append a specified number of values to a NumPy array.

    Parameters:
        arr (np.ndarray): The original NumPy array to which values will be appended.
        number_of_values (int): The number of values to append.

    Returns:
        np.ndarray: The updated NumPy array with the appended values.
    """
    for number in range(number_of_values):
        new_value = (number + 4) * 10
        arr = np.append(arr, [new_value])
    return arr
def main():
    arr = np.array([10,20,30])
    print(f"After appending element Array is {append_values(arr,5)}. ")
if __name__ == '__main__':
    main()

After appending element Array is [10 20 30 40 50 60 70 80]. 


## 10. Write a Python program to find the real and imaginary parts of an array of complexnumbers.
Expected Output:<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]<br>
Real part of the array:<br>
[ 1. 0.70710678]<br>
Imaginary part of the array:<br>
[ 0. 0.70710678]


In [94]:
def real_imaginary(arr):
    """
    Description:
    Extract the real and imaginary parts of a NumPy array of complex numbers.

    Parameters:
        arr (np.ndarray): A NumPy array containing complex numbers.

    Returns:
        list: A list containing two NumPy arrays:
            - The first array contains the real parts of the complex numbers.
            - The second array contains the imaginary parts of the complex numbers.
    """
    imag = np.imag(arr)  # Extract the imaginary part of each element
    real = np.real(arr)  # Extract the real part of each element
    return [real, imag]

def main():
    arr = [ 1.00000000+0.j, 0.70710678+0.70710678j]
    real_img =real_imaginary(np.array(arr))
    print(f"Real: {sum(real_img[0])}\nImaginary: {sum(real_img[1])}")

if __name__ == '__main__':
    main()

Real: 1.7071067800000002
Imaginary: 0.70710678


## 11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.
Expected Output:<br>
Size of the array: 3<br>
Length of one array element in bytes: 8<br>
Total bytes consumed by the elements of the array: 24<br>


In [109]:
def arr_props(arr):
    """
    Description:
    Calculate properties of a NumPy array.

    Parameters:
        arr (np.ndarray): A NumPy array.

    Returns:
        list: A list containing:
            - Size of the array (number of elements)
            - Length of one element in bytes
            - Total bytes consumed by the array
    """
    size = np.size(arr)  # Total number of elements in the array
    itemsize = arr.itemsize  # Size of one array element in bytes
    total_bytes = size * itemsize  # Total bytes consumed by all elements
    return [size, itemsize, total_bytes]

def main():
    arr = np.array([[1., 2., 3.], [4., 5., 6.]])
    props = arr_props(arr)
    print(f"Size of array: {props[0]}")
    print(f"Length of one array element in bytes: {props[1]}")
    print(f"Total bytes consumed by the elements of array: {props[2]}")

if __name__ == '__main__':
    main()


Size of array: 6
Length of one array element in bytes: 8
Total bytes consumed by the elements of array: 48


## 12. Write a Python program to find common values between two arrays.
Expected Output:<br>
Array1: [ 0 10 20 40 60]<br>
Array2: [10, 30, 40]<br>
Common values between two arrays:<br>
[10 40]


In [112]:
def intersection(arr1, arr2):
    """
    Find common values between two arrays.

    Parameters:
        arr1 (np.ndarray): First input array.
        arr2 (np.ndarray): Second input array.

    Returns:
        np.ndarray: Array of common values between the two input arrays.
    """
    return np.intersect1d(arr1, arr2)

def main():
    # Define the two arrays
    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])
    
    # Find common values
    common_values = intersection(array1, array2)
    
    # Print results
    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print("Common values between two arrays:")
    print(common_values)

if __name__ == '__main__':
    main()
    

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


## 13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
Expected Output:<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70, 90]<br>
Set difference between two arrays:<br>
[ 0 20 60 80]

In [113]:
def difference(arr1,arr2):
    """
    Description:
    Find set difference of two arrays.

    Parameters:
        arr1 (np.ndarray): First input array.
        arr2 (np.ndarray): Second input array.

    Returns:
        np.ndarray: return the sorted, unique values in array1 that are not in array2.
    """
    return np.setdiff1d(arr1,arr2)
def main():
    arr1 = np.array([ 0, 10, 20, 40, 60, 80])
    arr2 = np.array([ 10, 30, 40, 50, 70, 90])
    print(f"Set difference between two arrays:\n{difference(arr1,arr2)}")

if __name__ == '__main__':
    main()

Set difference between two arrays:
[ 0 20 60 80]


## 14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70]<br>
Unique values that are in only one (not both) of the input arrays:<br>
[ 0 20 30 50 60 70 80]

In [4]:
import numpy as np

def exor_array(arr1, arr2):
    """
    Description:
    Find the symmetric difference (exclusive OR) of two arrays.

    Parameters:
        arr1 (np.ndarray): First input array.
        arr2 (np.ndarray): Second input array.

    Returns:
        np.ndarray: Returns the sorted, unique values that are in either arr1 or arr2 but not in both.
    """
    # Use numpy's setxor1d to find the symmetric difference between arr1 and arr2
    return np.setxor1d(arr1, arr2)

def main():
    """
    Main function to demonstrate the use of the exor_array function.
    """
    # Define two numpy arrays
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70])

    # Print the symmetric difference between the two arrays
    print(f"Unique values that are in only one (not both) of the input arrays:\n{exor_array(array1, array2)}")

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


## 15. Write a Python program compare two arrays using numpy.
Array a: [1 2]<br>
Array b: [4 5]<br>
a > b<br>
[False False]<br>
a >= b<br>
[False False]<br>
a < b<br>
[ True True]<br>
a <= b<br>
[ True True]<br>


In [9]:
import numpy as np

def compare_array(arr1, arr2):
    """
    Description:
    Compare two arrays element-wise with various relational operators.

    Parameters:
        arr1 (np.ndarray): First input array.
        arr2 (np.ndarray): Second input array.

    Returns:
        list of np.ndarray: Contains four arrays representing the results of the comparisons: greater, greater_equal, less, less_equal.
    """
    # Perform element-wise comparisons between arr1 and arr2
    greater = arr1 > arr2
    greater_equal = arr1 >= arr2
    less = arr1 < arr2
    less_equal = arr1 <= arr2
    
    # Return the results as a list of arrays
    return [greater, greater_equal, less, less_equal]

def main():
    """
    Main function to demonstrate the use of the compare_array function.
    """
    # Define two numpy arrays
    array1 = np.array([1, 2])
    array2 = np.array([4, 5])
    
    # Compare the arrays using the compare_array function
    results = compare_array(array1, array2)
    
    # Print the input arrays
    print(array1, "\n", array2)
    
    # Print the results of the comparisons
    print(f"a > b\n{results[0]}\na >= b\n{results[1]}\na < b\n{results[2]}\na <= b\n{results[3]}")

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


[1 2] 
 [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


## 15. Write a Python program to save a NumPy array to a text file.

In [10]:
import numpy as np

def main():
    """
    Main function to demonstrate saving a numpy array to a text file.
    """
    # Define a numpy array with integer values
    array = np.array([2, 4, 6, 3, 5, 8, 6, 5])
    
    # Save the array to a text file named 'Welcome.txt'
    # Each element will be saved on a new line by default
    np.savetxt('Welcome.txt', array, fmt='%d')

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


## 16. Write a Python program to create a contiguous flattened array.
Original array:<br>
[[10 20 30]<br>
[20 40 50]]<br>
New flattened array:<br>
[10 20 30 20 40 50]


In [16]:
import numpy as np

def flatten_array(arr1, arr2):
    """
    Description:
    Flatten two arrays into a single one-dimensional array.

    Parameters:
        arr1 (np.ndarray): First input array.
        arr2 (np.ndarray): Second input array.

    Returns:
        np.ndarray: A one-dimensional array combining arr1 and arr2.
    """
    # Combine arr1 and arr2 into a 2D array and then flatten to 1D
    return np.array([arr1, arr2]).flatten()

def main():
    """
    Main function to demonstrate the use of the flatten_array function.
    """
    # Define two numpy arrays
    array1 = np.array([2, 4])
    array2 = np.array([1, 3])
    
    # Flatten the two arrays and print the result
    print(f"{flatten_array(array1, array2)}")

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


[2 4 1 3]


## 17. Write a Python program to change the data type of an array.
Expected Output:<br>
[[ 2 4 6]<br>
[ 6 8 10]]<br>
Data type of the array x is: int32<br>
New Type: float64<br>
[[ 2. 4. 6.]<br>
[ 6. 8. 10.]]<br>


In [23]:
import numpy as np

def main():
    """
    Main function to demonstrate changing the data type of a numpy array.
    """
    # Define a 2D numpy array with integer values
    array = np.array([[2, 4, 6], [6, 8, 10]])
    
    # Print the data type of the array elements
    print(f"Data type of array is {array.dtype}")
    
    # Convert the array elements to float type
    array = array.astype(float)
    
    # Print the new data type of the array elements
    print(f"New type: {array.dtype}")
    
    # Print the array with updated data type
    print(f"{array}")

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


Data type of array is int32
New type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


## 18. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
Expected Output:<br>
[[ 1. 0. 0.]<br>
[ 0. 1. 0.]<br>
[ 0. 0. 1.]]<br>


In [27]:
import numpy as np

def main():
    """
    Main function to demonstrate the use of numpy's diagflat function.
    """
    # Define a 1D numpy array
    arr = np.array([1, 1, 1])
    
    # Create a 2D diagonal array where the input array values are on the diagonal
    dia = np.diagflat(arr)
    
    # Print the resulting diagonal matrix
    print(dia)

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 19. Write a Python program to create an array which looks like below array.
Expected Output: <br>
[[ 0. 0. 0.]<br>
[ 1. 0. 0.]<br>
[ 1. 1. 0.]<br>
[ 1. 1. 1.]]


In [53]:
import numpy as np

def main():
    """
    Main function to demonstrate various numpy array operations.
    """
    # Create a 4x3 array filled with ones
    arr = np.ones((4, 3))
    
    # Keep the upper triangular part of the array (including the diagonal)
    arr = np.triu(arr)
    
    # Flip the array horizontally (left-to-right)
    arr = np.fliplr(arr)
    
    # Flip the array vertically (top-to-bottom)
    arr = np.flipud(arr)
    
    # Print the resulting array
    print(arr)

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## 20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:,<br>
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])<br>
Expected Output:<br>
[[ 0 1 3 0 2 4]<br>
[ 5 7 9 6 8 10]]


In [60]:
import numpy as np

def main():
    """
    Main function to demonstrate the use of numpy's concatenate function.
    """
    # Define two 2D lists
    array1 = [[0, 1, 3], [5, 7, 9]]
    array2 = [[0, 2, 4], [6, 8, 10]]
    
    # Concatenate the two arrays along the columns (axis=1)
    concatenated_array = np.concatenate((array1, array2), axis=1)
    
    # Print the concatenated array
    print(f"Concatenated array:\n{concatenated_array}")

if __name__ == '__main__':
    # Execute main function if this script is run directly
    main()


Concatenated array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
