'''<br><br>


    @Author: Shivraj Yelave
    @Date: 5-08-24
    @Last modified by: Shivraj Yelave
    @Last modified time:
    @Title: Python Numpy Programs 
<br><br>


'''

In [12]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. <br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32] <br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [13]:
def main():
    lst = [12.23, 13.32, 100, 36.32]
    arr = np.array(lst)
    print("Array:",arr)

if __name__ == '__main__':
    main()

Array: [ 12.23  13.32 100.    36.32]


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]


In [18]:
def main():
    arr = np.arange(2,11)
    print("3x3 Array: \n",arr.reshape(3,3))
if __name__ == '__main__':
    main()

3x3 Array: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
